- name: Upgrade kubernetes packages for Centos
  yum:
    name: "{{ packages }}"
    enablerepo: kubernetes
    pkgs:
    - kubelet-{{kubeadm_version}}
    - kubectl-{{kubeadm_version}}
    - kubeadm-{{kubeadm_version}}
  when: ansible_os_family == "RedHat"

- name: Upgrade kubernetes packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ pkgs }}"
    update_cache: yes
    state: present
    force: yes
  with_items: "{{ pkgs }}"

- name: "Update kubeadm config yaml"
  copy:
    content: "{{ kubeadm_config_options | to_nice_yaml }}"
    dest: /tmp/kubeadm-config.yaml
    mode: 0644

- name: "Kubeadm upgrade plan"
  # shell: kubeadm upgrade plan --config /tmp/kubeadm-config.yaml  --print-config
  shell: kubeadm upgrade plan
  register: rslt



- name: "Kubeadm upgrade dry-run command"
  # shell: kubeadm upgrade apply {{kubernetes_version}} --config /tmp/kubeadm-config.yaml --dry-run
  shell: kubeadm upgrade apply {{kubernetes_version}} --dry-run --force
  register: rslt



- name: "Kubeadm upgrade"
  #shell: kubeadm upgrade apply -f --config /tmp/kubeadm-config.yaml {{kubernetes_version}} 
  shell: kubeadm upgrade apply {{kubernetes_version}} -y --force
  register: rslt



- name: Restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
    enabled: yes

#- name: Upgrade masters sequentially
#  include_tasks: "upgrade_masters.yaml"
#  with_items: "{{ groups['k8s-master-replicas'] }}"
#  when: "hostvars[host_item].inventory_hostname == inventory_hostname"
#  loop_control:
#      loop_var: host_item
