apiVersion: v1
kind: Secret
metadata:
  name: bigip-login
  namespace: kube-system
type: Opaque
data:
  url: aHR0cHM6Ly8xNzIuMjUuMzAuMTAx
  username: Y2lzLXVzZXIK
  password: NU5tNzdjYm1YJkNra3FQCg==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigip-ctlr
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole
rules:
- apiGroups: ["", "extensions"]
  resources: ["nodes", "services", "endpoints", "namespaces", "ingresses", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions"]
  resources: ["configmaps", "events", "ingresses/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["", "extensions"]
  resources: ["secrets"]
  resourceNames: ["<secret-containing-bigip-login>"]
  verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip-ctlr-clusterrole
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: bigip-ctlr
  namespace: kube-system
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      labels:
        app: k8s-bigip-ctlr
      name: k8s-bigip-ctlr
    spec:
      containers:
      - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=172.19.46.5
        - --bigip-partition=DR
        - --pool-member-type=cluster
        - --flannel-name=/Common/fl-vxlan
        - --insecure=true
        - --as3-validation=false
        - --agent=cccl
        command:
        - /app/bin/k8s-bigip-ctlr
        env:
        - name: http_proxy
          value: http://172.19.11.30:80/
        - name: ftp_proxy
          value: ftp://172.19.11.30:80/
        - name: https_proxy
          value: http://172.19.11.30:80/
        - name: HTTPS_PROXY
          value: http://172.19.11.30:80/
        - name: no_proxy
          value: .interswitch.com,localhost,127.0.0.1,172.19.46.0/24,172.19.46.128,172.19.46.129,172.19.46.121,172.19.46.122,172.19.46.123,172.19.46.124,10.96.0.0/12,10.236.0.0/16
        - name: NO_PROXY
          value: .interswitch.com,localhost,127.0.0.1,172.19.46.0/24,172.19.46.121,172.19.46.122,172.19.46.128,172.19.46.129,172.19.46.123,172.19.46.124,10.96.0.0/12,10.236.0.0/16
        - name: BIGIP_USERNAME
          value: dr-cis-user
        - name: BIGIP_PASSWORD
          value: 5Nm77cbmX&CkkqP
        image: f5networks/k8s-bigip-ctlr
        name: k8s-bigip-ctlr
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: bigip-login
      restartPolicy: Always
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr


apiVersion: v1
kind: Node
metadata:
  name: bigip
  annotations:
    #Replace IP with Self-IP for your deployment
    flannel.alpha.coreos.com/public-ip: "172.19.46.5"
    #Replace MAC with your BIG-IP Flannel VXLAN Tunnel MAC
    flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"00:23:e9:e6:2e:02"}'
    flannel.alpha.coreos.com/backend-type: "vxlan"
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
spec:
  #Replace Subnet with your BIG-IP Flannel Subnet
  podCIDR: "10.190.20.0/24"
